
language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  global:
    - GCC_VERSION="4.9"
  matrix:
    - BUILD_TYPE=Release

matrix:
  exclude:
    - compiler: gcc
      os: osx

before_install:
  - sh projects/scripts/travis-install.sh
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

  - sudo apt-get update -qq
install:
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq "g++-${GCC_VERSION}"; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi

  - export PATH=/usr/bin:$PATH
  - cd projects
  - cmake -GUnix\ Makefiles -HCMake -Bbuild -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX
  - cd build
  - make -j2
  - cd ../..

script:
  - cd projects/build
  - ./rxcppv2_test --success -r compact
  - cd ../..

branches:
  only:
    - master

notifications:
  recipients:
    - kirk.shoop@microsoft.com
  email:
    on_success: always
    on_failure: always
