
language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
    - CMAKE_BUILD_TYPE=RelWithDebInfo
#    - CMAKE_BUILD_TYPE=Debug

matrix:
  allow_failures:
    - compiler: clang
      os: linux
  exclude:
    - compiler: gcc
      os: osx

before_install:
  - sh projects/scripts/travis-install.sh

install:
  - $CXX --version
  - /usr/local/bin/cmake --version
  - cd projects
  - /usr/local/bin/cmake -GUnix\ Makefiles -HCMake -Bbuild -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX
  - cd ..

script:
  - cd projects/build
  - make -j2
  - cd ../..

#after_success:
#  - projects/build/rxcppv2_test

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - kirk.shoop@microsoft.com
    on_success: always
    on_failure: always
