language: cpp
os:
- linux
- osx
compiler:
- clang
- gcc
env:
  matrix:
  - CMAKE_BUILD_TYPE=RelWithDebInfo
  global:
    secure: FNZOWYO89qsT9kQKngrYbpnqCTMCSCSQ2rnZ3l17KHctOfS554TTDS+dfxPYz2XHm6azYDVcyBSs2gWJ6TmXZZZqEfr3X4VV4ooAa9PoeIkvVlT654zjZwxeXPYXrHFXZh/ImLUGWjsxRaUHYOv5SzyNGcZv07dtLKVd0ykhbH4=
matrix:
  allow_failures:
  - compiler: clang
    os: linux
  exclude:
  - compiler: gcc
    os: osx
before_install:
- sh projects/scripts/travis-install.sh
install:
- "$CXX --version"
- "/usr/local/bin/cmake --version"
- cd projects
- "/usr/local/bin/cmake -GUnix\\ Makefiles -HCMake -Bbuild -DCMAKE_C_COMPILER=$CC
  -DCMAKE_CXX_COMPILER=$CXX"
- cd ..
script:
- cd projects/build
- make -j1
- cd ../..
after_success:
- sh projects/scripts/travis-doxygen.sh
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - kirk.shoop@microsoft.com
    on_success: always
    on_failure: always
